apiVersion: v1
kind: Service
metadata:
  name: melora-service
spec:
  type: NodePort
  selector:
    app: melora
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
